### ISSUE TITLE
How to add aliases

### ISSUE THREAD

**Issue by KatSick** [lukeed/fly-kit-preact#2]
I wan't to use some react libraries with this boilerplate, how a can configure aliases ?

**Comment by lukeed** [comment]
Hey, it's pretty easy 😄 

1. Install [`rollup-plugin-alias`](https://github.com/frostney/rollup-plugin-alias)

  ```
  npm install --save-dev rollup-plugin-alias
  ```

2. Go to `config/rollup.js` & import the new plugin. Your file should look something like this:

  ```js
  const alias = require('rollup-plugin-alias');
  const buble = require('rollup-plugin-buble');
  const replace = require('rollup-plugin-replace');
  const resolve = require('rollup-plugin-node-resolve');

  module.exports = {
    rollup: {
      plugins: [
        alias({
          'react': 'preact-compat',
          'react-dom': 'preact-compat'
        }),
        buble({
          jsx: 'h',
          transforms: {
            modules: false
          }
        }),
        replace({'process.env.NODE_ENV': JSON.stringify('production')}),
        resolve({browser: true, jsnext: true})
      ]
    },
    bundle: {
      format: 'iife',
      sourceMap: true
    }
  };
  ```

3. Then, of course, you have to install `preact-compat`

  ```
  npm install --save preact-compat
  ```

**Comment by KatSick** [comment]
Many thanks. We can close this topic

**Comment by lukeed** [comment]
I've now added this to the repo 😄 The only difference is that I've used `preact/aliases` instead of `preact-compat` because it fits most cases.

**Comment by lukeed** [comment]
Source: https://twitter.com/_developit/status/817868067137081345
