### ISSUE TITLE
How to use any state managment library ? (redux\mobx)

### ISSUE THREAD

**Issue by KatSick** [lukeed/fly-kit-preact#3]
I get error when i try to do

`import { connect } from 'react-redux'`

or 

`import { observer } from 'mobx-react`

Error for mobx is:
```
[20:36:35] scripts failed due to Error: Module /Users/ochervak/Projects/fly-kit-preact/node_modules/mobx-react/index.js does not export observer (imported by /Users/ochervak/Projects/fly-kit-preact/src/scripts/views/pages/home.js)
```

How can i fix this ?

**Comment by lukeed** [comment]
Hey,

You need to install `rollup-plugin-commonjs` and then follow the instructions [here](https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports).

Most likely, you need to add:

```js
// config/rollup.js
const commonjs = require('rollup-plugin-commonjs');

module.exports = {
  // ...
  plugins: [
    alias(...),
    buble(...),
    commonjs({
      namedExports: {
        'react-redux': ['observer']
      }
    })
    // ...
  ]
}
```

BY the way, there are [`preact-redux`](https://github.com/developit/preact-redux) and [`mobx-preact`](https://github.com/nightwolfz/mobx-preact) libraries!
